spring:
  datasource:
    url: jdbc:mysql://101.132.181.196:3306/mmall?characterEncoding=utf-8&useSSL=false
    username: root
    password: yedeyang
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 101.132.181.196
#    password: yedeyang
    port: 6379

app:
  jwtSecret:
    JWTSuperSecretKey
  jwtExpirationInMs:
    604800000

  aliyun:
    sms:
      accessKeySecret: IDUW6Z53NQJWreaGa9gudZVto8TGw3
      accessKeyId: LTAI5vhh9FqlmkKp
